import type {
  Category,
  Story,
  Entity,
  CategoryId,
} from '@/types';

export const categories: Category[] = [
  { id: 'politics', label: 'Politics', slug: 'politics' },
  { id: 'technology', label: 'Technology', slug: 'technology' },
  { id: 'science', label: 'Science', slug: 'science' },
  { id: 'business', label: 'Business', slug: 'business' },
  { id: 'world', label: 'World', slug: 'world' },
  { id: 'india', label: 'India', slug: 'india' },
  { id: 'education', label: 'Education', slug: 'education' },
  { id: 'health', label: 'Health', slug: 'health' },
  { id: 'environment', label: 'Environment', slug: 'environment' },
  { id: 'culture', label: 'Culture', slug: 'culture' },
  { id: 'sports', label: 'Sports', slug: 'sports' },
];

export function getCategoryLabel(id: CategoryId): string {
  return categories.find((c) => c.id === id)?.label ?? id;
}

export const demoEntities: Entity[] = [
  {
    id: 'narendra-modi',
    name: 'Narendra Modi',
    type: 'person',
    subtitle: 'Prime Minister of India',
    description:
      'Narendra Modi is the current Prime Minister of India, in office since 2014. He leads the Bharatiya Janata Party (BJP) and represents the Varanasi constituency in Parliament.',
    relatedEntityIds: ['bjp', 'india', 'government-of-india', 'parliament-of-india'],
    mentionCount: 342,
    mentionsOverTime: [
      { date: '2026-09-19', count: 12 },
      { date: '2026-09-20', count: 18 },
      { date: '2026-09-21', count: 24 },
      { date: '2026-09-22', count: 31 },
      { date: '2026-09-23', count: 28 },
      { date: '2026-09-24', count: 42 },
      { date: '2026-09-25', count: 38 },
    ],
  },
  {
    id: 'elon-musk',
    name: 'Elon Musk',
    type: 'person',
    subtitle: 'CEO of Tesla, SpaceX, and X (formerly Twitter)',
    description:
      'Elon Musk is a technology entrepreneur leading Tesla, SpaceX, and X. He is one of the most covered figures in technology and business media worldwide.',
    relatedEntityIds: ['tesla', 'spacex', 'x-corp', 'openai'],
    mentionCount: 287,
    mentionsOverTime: [
      { date: '2026-09-19', count: 22 },
      { date: '2026-09-20', count: 19 },
      { date: '2026-09-21', count: 31 },
      { date: '2026-09-22', count: 27 },
      { date: '2026-09-23', count: 35 },
      { date: '2026-09-24', count: 44 },
      { date: '2026-09-25', count: 41 },
    ],
  },
  {
    id: 'sam-altman',
    name: 'Sam Altman',
    type: 'person',
    subtitle: 'CEO of OpenAI',
    description:
      'Sam Altman is the CEO of OpenAI, one of the leading artificial intelligence research companies. He is a central figure in the AI industry and frequently covered in technology media.',
    relatedEntityIds: ['openai', 'microsoft', 'artificial-intelligence'],
    mentionCount: 198,
    mentionsOverTime: [
      { date: '2026-09-19', count: 8 },
      { date: '2026-09-20', count: 14 },
      { date: '2026-09-21', count: 19 },
      { date: '2026-09-22', count: 22 },
      { date: '2026-09-23', count: 26 },
      { date: '2026-09-24', count: 31 },
      { date: '2026-09-25', count: 35 },
    ],
  },
  {
    id: 'joe-biden',
    name: 'Joe Biden',
    type: 'person',
    subtitle: 'President of the United States',
    description:
      'Joe Biden is the 46th President of the United States. His administration focuses on infrastructure, foreign policy, and economic recovery.',
    relatedEntityIds: ['united-states', 'white-house', 'democratic-party'],
    mentionCount: 256,
    mentionsOverTime: [
      { date: '2026-09-19', count: 18 },
      { date: '2026-09-20', count: 22 },
      { date: '2026-09-21', count: 19 },
      { date: '2026-09-22', count: 25 },
      { date: '2026-09-23', count: 31 },
      { date: '2026-09-24', count: 28 },
      { date: '2026-09-25', count: 33 },
    ],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    type: 'organization',
    subtitle: 'AI Research Company',
    description:
      'OpenAI is an artificial intelligence research and deployment company known for developing the GPT series of large language models and ChatGPT.',
    relatedEntityIds: ['sam-altman', 'microsoft', 'artificial-intelligence'],
    mentionCount: 312,
    mentionsOverTime: [
      { date: '2026-09-19', count: 15 },
      { date: '2026-09-20', count: 21 },
      { date: '2026-09-21', count: 28 },
      { date: '2026-09-22', count: 33 },
      { date: '2026-09-23', count: 30 },
      { date: '2026-09-24', count: 38 },
      { date: '2026-09-25', count: 42 },
    ],
  },
  {
    id: 'tesla',
    name: 'Tesla',
    type: 'organization',
    subtitle: 'Electric Vehicle Manufacturer',
    description:
      'Tesla is an electric vehicle and clean energy company led by Elon Musk. It designs and manufactures electric cars, battery storage, and solar products.',
    relatedEntityIds: ['elon-musk', 'spacex'],
    mentionCount: 174,
    mentionsOverTime: [
      { date: '2026-09-19', count: 10 },
      { date: '2026-09-20', count: 12 },
      { date: '2026-09-21', count: 15 },
      { date: '2026-09-22', count: 18 },
      { date: '2026-09-23', count: 14 },
      { date: '2026-09-24', count: 20 },
      { date: '2026-09-25', count: 24 },
    ],
  },
  {
    id: 'spacex',
    name: 'SpaceX',
    type: 'organization',
    subtitle: 'Aerospace Manufacturer',
    description:
      'SpaceX is a private aerospace manufacturer and space transportation company founded by Elon Musk. It develops the Falcon and Starship launch vehicles.',
    relatedEntityIds: ['elon-musk', 'nasa', 'isro'],
    mentionCount: 142,
    mentionsOverTime: [
      { date: '2026-09-19', count: 8 },
      { date: '2026-09-20', count: 10 },
      { date: '2026-09-21', count: 13 },
      { date: '2026-09-22', count: 16 },
      { date: '2026-09-23', count: 12 },
      { date: '2026-09-24', count: 18 },
      { date: '2026-09-25', count: 22 },
    ],
  },
  {
    id: 'microsoft',
    name: 'Microsoft',
    type: 'organization',
    subtitle: 'Technology Corporation',
    description:
      'Microsoft is a multinational technology corporation producing software, consumer electronics, and cloud services. It is a major investor in OpenAI.',
    relatedEntityIds: ['openai', 'sam-altman', 'artificial-intelligence'],
    mentionCount: 156,
    mentionsOverTime: [
      { date: '2026-09-19', count: 9 },
      { date: '2026-09-20', count: 11 },
      { date: '2026-09-21', count: 14 },
      { date: '2026-09-22', count: 17 },
      { date: '2026-09-23', count: 15 },
      { date: '2026-09-24', count: 21 },
      { date: '2026-09-25', count: 19 },
    ],
  },
  {
    id: 'bjp',
    name: 'BJP',
    type: 'organization',
    subtitle: 'Bharatiya Janata Party',
    description:
      'The Bharatiya Janata Party is one of the two major political parties in India, currently the ruling party led by Prime Minister Narendra Modi.',
    relatedEntityIds: ['narendra-modi', 'india', 'parliament-of-india'],
    mentionCount: 189,
    mentionsOverTime: [
      { date: '2026-09-19', count: 11 },
      { date: '2026-09-20', count: 14 },
      { date: '2026-09-21', count: 18 },
      { date: '2026-09-22', count: 22 },
      { date: '2026-09-23', count: 19 },
      { date: '2026-09-24', count: 25 },
      { date: '2026-09-25', count: 28 },
    ],
  },
  {
    id: 'isro',
    name: 'ISRO',
    type: 'organization',
    subtitle: 'Indian Space Research Organisation',
    description:
      'The Indian Space Research Organisation is the national space agency of India, known for its cost-effective missions including Chandrayaan and Mangalyaan.',
    relatedEntityIds: ['india', 'spacex', 'nasa'],
    mentionCount: 134,
    mentionsOverTime: [
      { date: '2026-09-19', count: 7 },
      { date: '2026-09-20', count: 9 },
      { date: '2026-09-21', count: 12 },
      { date: '2026-09-22', count: 15 },
      { date: '2026-09-23', count: 11 },
      { date: '2026-09-24', count: 17 },
      { date: '2026-09-25', count: 21 },
    ],
  },
  {
    id: 'supreme-court',
    name: 'Supreme Court',
    type: 'institution',
    subtitle: 'Supreme Court of India',
    description:
      'The Supreme Court of India is the highest judicial authority in the country, handling constitutional matters and appeals from lower courts.',
    relatedEntityIds: ['india', 'government-of-india', 'parliament-of-india'],
    mentionCount: 98,
    mentionsOverTime: [
      { date: '2026-09-19', count: 5 },
      { date: '2026-09-20', count: 7 },
      { date: '2026-09-21', count: 9 },
      { date: '2026-09-22', count: 11 },
      { date: '2026-09-23', count: 8 },
      { date: '2026-09-24', count: 13 },
      { date: '2026-09-25', count: 15 },
    ],
  },
  {
    id: 'nasa',
    name: 'NASA',
    type: 'institution',
    subtitle: 'National Aeronautics and Space Administration',
    description:
      'NASA is the United States government agency responsible for civilian space programs, aerospace research, and space exploration.',
    relatedEntityIds: ['spacex', 'isro', 'united-states'],
    mentionCount: 121,
    mentionsOverTime: [
      { date: '2026-09-19', count: 6 },
      { date: '2026-09-20', count: 8 },
      { date: '2026-09-21', count: 10 },
      { date: '2026-09-22', count: 13 },
      { date: '2026-09-23', count: 11 },
      { date: '2026-09-24', count: 15 },
      { date: '2026-09-25', count: 18 },
    ],
  },
  {
    id: 'parliament-of-india',
    name: 'Parliament of India',
    type: 'institution',
    subtitle: 'Supreme Legislative Body',
    description:
      'The Parliament of India is the supreme legislative body, consisting of the President, the Lok Sabha, and the Rajya Sabha.',
    relatedEntityIds: ['narendra-modi', 'bjp', 'government-of-india'],
    mentionCount: 87,
    mentionsOverTime: [
      { date: '2026-09-19', count: 4 },
      { date: '2026-09-20', count: 6 },
      { date: '2026-09-21', count: 8 },
      { date: '2026-09-22', count: 10 },
      { date: '2026-09-23', count: 7 },
      { date: '2026-09-24', count: 12 },
      { date: '2026-09-25', count: 14 },
    ],
  },
  {
    id: 'white-house',
    name: 'The White House',
    type: 'institution',
    subtitle: 'Executive Residence of the United States',
    description:
      'The White House is the official residence and workplace of the President of the United States, central to US executive decision-making.',
    relatedEntityIds: ['joe-biden', 'united-states', 'democratic-party'],
    mentionCount: 102,
    mentionsOverTime: [
      { date: '2026-09-19', count: 6 },
      { date: '2026-09-20', count: 8 },
      { date: '2026-09-21', count: 11 },
      { date: '2026-09-22', count: 14 },
      { date: '2026-09-23', count: 10 },
      { date: '2026-09-24', count: 16 },
      { date: '2026-09-25', count: 19 },
    ],
  },
  {
    id: 'india',
    name: 'India',
    type: 'location',
    subtitle: 'Republic of India',
    description:
      'India is a country in South Asia, the most populous nation in the world and the largest democracy, with a rapidly growing economy and active media landscape.',
    relatedEntityIds: ['narendra-modi', 'bjp', 'isro', 'supreme-court'],
    mentionCount: 421,
    mentionsOverTime: [
      { date: '2026-09-19', count: 28 },
      { date: '2026-09-20', count: 35 },
      { date: '2026-09-21', count: 42 },
      { date: '2026-09-22', count: 48 },
      { date: '2026-09-23', count: 44 },
      { date: '2026-09-24', count: 52 },
      { date: '2026-09-25', count: 56 },
    ],
  },
  {
    id: 'united-states',
    name: 'United States',
    type: 'location',
    subtitle: 'United States of America',
    description:
      'The United States is a federal republic of 50 states in North America, the world\'s largest economy and a central player in global geopolitics.',
    relatedEntityIds: ['joe-biden', 'white-house', 'nasa'],
    mentionCount: 367,
    mentionsOverTime: [
      { date: '2026-09-19', count: 22 },
      { date: '2026-09-20', count: 28 },
      { date: '2026-09-21', count: 33 },
      { date: '2026-09-22', count: 38 },
      { date: '2026-09-23', count: 35 },
      { date: '2026-09-24', count: 41 },
      { date: '2026-09-25', count: 44 },
    ],
  },
  {
    id: 'delhi',
    name: 'Delhi',
    type: 'location',
    subtitle: 'National Capital Territory of Delhi',
    description:
      'Delhi is the capital territory of India, housing the central government, Parliament, and the Supreme Court. It is a major political and media center.',
    relatedEntityIds: ['india', 'parliament-of-india', 'supreme-court'],
    mentionCount: 145,
    mentionsOverTime: [
      { date: '2026-09-19', count: 8 },
      { date: '2026-09-20', count: 10 },
      { date: '2026-09-21', count: 13 },
      { date: '2026-09-22', count: 16 },
      { date: '2026-09-23', count: 12 },
      { date: '2026-09-24', count: 18 },
      { date: '2026-09-25', count: 22 },
    ],
  },
  {
    id: 'washington',
    name: 'Washington',
    type: 'location',
    subtitle: 'Washington, D.C.',
    description:
      'Washington, D.C. is the capital of the United States, home to the federal government, the White House, and major policy institutions.',
    relatedEntityIds: ['united-states', 'white-house', 'joe-biden'],
    mentionCount: 132,
    mentionsOverTime: [
      { date: '2026-09-19', count: 7 },
      { date: '2026-09-20', count: 9 },
      { date: '2026-09-21', count: 12 },
      { date: '2026-09-22', count: 15 },
      { date: '2026-09-23', count: 11 },
      { date: '2026-09-24', count: 17 },
      { date: '2026-09-25', count: 20 },
    ],
  },
  {
    id: 'government-of-india',
    name: 'Government of India',
    type: 'institution',
    subtitle: 'Union Government',
    description:
      'The Government of India is the union government of the Republic of India, led by the Prime Minister and the Council of Ministers.',
    relatedEntityIds: ['narendra-modi', 'bjp', 'parliament-of-india', 'india'],
    mentionCount: 167,
    mentionsOverTime: [
      { date: '2026-09-19', count: 9 },
      { date: '2026-09-20', count: 12 },
      { date: '2026-09-21', count: 15 },
      { date: '2026-09-22', count: 18 },
      { date: '2026-09-23', count: 14 },
      { date: '2026-09-24', count: 20 },
      { date: '2026-09-25', count: 24 },
    ],
  },
  {
    id: 'artificial-intelligence',
    name: 'Artificial Intelligence',
    type: 'organization',
    subtitle: 'Technology Domain',
    description:
      'Artificial Intelligence refers to the development of computer systems capable of performing tasks that typically require human intelligence, including language processing, image recognition, and decision-making.',
    relatedEntityIds: ['openai', 'sam-altman', 'microsoft'],
    mentionCount: 298,
    mentionsOverTime: [
      { date: '2026-09-19', count: 14 },
      { date: '2026-09-20', count: 19 },
      { date: '2026-09-21', count: 25 },
      { date: '2026-09-22', count: 30 },
      { date: '2026-09-23', count: 27 },
      { date: '2026-09-24', count: 35 },
      { date: '2026-09-25', count: 39 },
    ],
  },
  {
    id: 'democratic-party',
    name: 'Democratic Party',
    type: 'organization',
    subtitle: 'US Political Party',
    description:
      'The Democratic Party is one of the two major political parties in the United States, currently holding the presidency under Joe Biden.',
    relatedEntityIds: ['joe-biden', 'white-house', 'united-states'],
    mentionCount: 113,
    mentionsOverTime: [
      { date: '2026-09-19', count: 6 },
      { date: '2026-09-20', count: 8 },
      { date: '2026-09-21', count: 11 },
      { date: '2026-09-22', count: 14 },
      { date: '2026-09-23', count: 10 },
      { date: '2026-09-24', count: 16 },
      { date: '2026-09-25', count: 19 },
    ],
  },
  {
    id: 'x-corp',
    name: 'X (Twitter)',
    type: 'organization',
    subtitle: 'Social Media Platform',
    description:
      'X, formerly known as Twitter, is a social media platform owned by Elon Musk. It is a major source of real-time news and public discourse.',
    relatedEntityIds: ['elon-musk'],
    mentionCount: 128,
    mentionsOverTime: [
      { date: '2026-09-19', count: 7 },
      { date: '2026-09-20', count: 9 },
      { date: '2026-09-21', count: 12 },
      { date: '2026-09-22', count: 15 },
      { date: '2026-09-23', count: 11 },
      { date: '2026-09-24', count: 17 },
      { date: '2026-09-25', count: 20 },
    ],
  },
];

const now = new Date('2026-09-25T10:00:00Z');

function hoursAgo(h: number): string {
  return new Date(now.getTime() - h * 3600_000).toISOString();
}

export const demoStories: Story[] = [
  {
    id: 'story-1',
    title: 'AI Companies Race to Develop Next Generation of Frontier Models',
    summary:
      'Major AI companies including OpenAI, Google DeepMind, and Anthropic are accelerating development of frontier AI models with enhanced reasoning capabilities, sparking renewed debate over safety, regulation, and the pace of deployment.',
    detailedSummary:
      'A wave of announcements from leading AI companies has intensified the global race to build next-generation frontier models. OpenAI, Google DeepMind, and Anthropic have all signaled major upgrades to their flagship models, with a focus on improved reasoning, multimodal capabilities, and agentic behavior. The developments come as governments worldwide grapple with how to regulate increasingly powerful AI systems. The EU AI Act is entering its enforcement phase, while the US is considering new federal guidelines. Industry leaders have called for coordinated international frameworks to ensure safety without stifling innovation. Critics argue that the pace of deployment is outstripping safety research, pointing to recent incidents of model misbehavior in production environments.',
    keyDevelopments: [
      'OpenAI announced a new model with enhanced reasoning and agentic task completion',
      'Google DeepMind revealed improvements to Gemini\'s multimodal capabilities',
      'EU AI Act enforcement phase begins, requiring compliance from high-risk system providers',
      'US Congress considers bipartisan AI safety legislation',
      'Industry consortium publishes open safety benchmarks for frontier models',
    ],
    category: 'technology',
    categoryLabel: 'Technology',
    trendingScore: 94,
    sourceCount: 18,
    publishedAt: hoursAgo(2),
    updatedAt: hoursAgo(0.2),
    entityIds: ['openai', 'sam-altman', 'microsoft', 'artificial-intelligence', 'elon-musk'],
    isBreaking: true,
    sources: [
      { sourceId: 'bbc', sourceName: 'BBC', sourceUrl: 'https://bbc.com', articleUrl: 'https://bbc.com/news/ai-frontier-models', articleHeadline: 'AI giants unveil next wave of frontier models', publishedAt: hoursAgo(2) },
      { sourceId: 'ndtv', sourceName: 'NDTV', sourceUrl: 'https://ndtv.com', articleUrl: 'https://ndtv.com/technology/ai-race-frontier-models', articleHeadline: 'AI Race: Companies Sprint to Build Next-Gen Models', publishedAt: hoursAgo(3) },
      { sourceId: 'reuters', sourceName: 'Reuters', sourceUrl: 'https://reuters.com', articleUrl: 'https://reuters.com/technology/ai-frontier-models-2026', articleHeadline: 'OpenAI, Google, Anthropic accelerate frontier model development', publishedAt: hoursAgo(2) },
      { sourceId: 'telegraph', sourceName: 'The Telegraph', sourceUrl: 'https://telegraph.co.uk', articleUrl: 'https://telegraph.co.uk/technology/ai-frontier-race', articleHeadline: 'The AI arms race enters a new phase', publishedAt: hoursAgo(4) },
      { sourceId: 'the-hindu', sourceName: 'The Hindu', sourceUrl: 'https://thehindu.com', articleUrl: 'https://thehindu.com/sci-tech/technology/ai-frontier-models', articleHeadline: 'Frontier AI models: The global race intensifies', publishedAt: hoursAgo(3) },
      { sourceId: 'indian-express', sourceName: 'Indian Express', sourceUrl: 'https://indianexpress.com', articleUrl: 'https://indianexpress.com/technology/ai-frontier-models-2026', articleHeadline: 'AI companies push boundaries with new frontier models', publishedAt: hoursAgo(5) },
      { sourceId: 'cnn', sourceName: 'CNN', sourceUrl: 'https://cnn.com', articleUrl: 'https://cnn.com/technology/ai-frontier-models', articleHeadline: 'The next AI frontier: What you need to know', publishedAt: hoursAgo(3) },
      { sourceId: 'al-jazeera', sourceName: 'Al Jazeera', sourceUrl: 'https://aljazeera.com', articleUrl: 'https://aljazeera.com/technology/ai-frontier-models', articleHeadline: 'AI race raises safety concerns as models grow more powerful', publishedAt: hoursAgo(4) },
    ],
  },
  {
    id: 'story-2',
    title: 'Parliament Passes Landmark Data Protection Legislation',
    summary:
      'After years of deliberation, Parliament has passed a comprehensive data protection bill establishing new rights for citizens and obligations for companies handling personal data.',
    detailedSummary:
      'The Parliament has passed a landmark data protection bill that establishes a comprehensive framework for the handling of personal data. The legislation grants citizens new rights including data portability, the right to be forgotten, and explicit consent requirements. Companies will face stringent obligations including mandatory breach notifications and data localization for certain categories. The bill was passed after extensive consultation with civil society, industry, and legal experts. The government has indicated a phased implementation approach, with large platforms required to comply within six months.',
    keyDevelopments: [
      'Bill passed with bipartisan support after three years of deliberation',
      'Establishes right to data portability and right to be forgotten',
      'Mandatory breach notification within 72 hours',
      'Data localization requirements for sensitive personal data',
      'Phased implementation: large platforms first, small entities later',
    ],
    category: 'politics',
    categoryLabel: 'Politics',
    trendingScore: 88,
    sourceCount: 14,
    publishedAt: hoursAgo(3),
    updatedAt: hoursAgo(0.5),
    entityIds: ['parliament-of-india', 'government-of-india', 'narendra-modi', 'bjp', 'india'],
    sources: [
      { sourceId: 'ndtv', sourceName: 'NDTV', sourceUrl: 'https://ndtv.com', articleUrl: 'https://ndtv.com/india-news/data-protection-bill-passed', articleHeadline: 'Parliament passes landmark data protection bill', publishedAt: hoursAgo(3) },
      { sourceId: 'the-hindu', sourceName: 'The Hindu', sourceUrl: 'https://thehindu.com', articleUrl: 'https://thehindu.com/news/national/data-protection-bill', articleHeadline: 'Data Protection Bill passed by Parliament', publishedAt: hoursAgo(3) },
      { sourceId: 'indian-express', sourceName: 'Indian Express', sourceUrl: 'https://indianexpress.com', articleUrl: 'https://indianexpress.com/article/india/data-protection-law', articleHeadline: 'Parliament clears data protection legislation', publishedAt: hoursAgo(4) },
      { sourceId: 'times-now', sourceName: 'Times Now', sourceUrl: 'https://timesnownews.com', articleUrl: 'https://timesnownews.com/india/data-protection-bill', articleHeadline: 'Historic: Parliament passes data protection bill', publishedAt: hoursAgo(3) },
      { sourceId: 'republic', sourceName: 'Republic', sourceUrl: 'https://republicworld.com', articleUrl: 'https://republicworld.com/india-news/data-protection-bill', articleHeadline: 'Data protection bill becomes law', publishedAt: hoursAgo(4) },
      { sourceId: 'abp', sourceName: 'ABP', sourceUrl: 'https://abplive.com', articleUrl: 'https://abplive.com/india-news/data-protection-bill-passed', articleHeadline: 'Parliament passes data protection law', publishedAt: hoursAgo(5) },
    ],
  },
  {
    id: 'story-3',
    title: 'ISRO Successfully Launches Advanced Earth Observation Satellite',
    summary:
      'The Indian Space Research Organisation has successfully launched an advanced Earth observation satellite, enhancing India\'s remote sensing and disaster management capabilities.',
    detailedSummary:
      'ISRO has successfully placed an advanced Earth observation satellite into orbit, marking another milestone in India\'s growing space program. The satellite, equipped with high-resolution imaging capabilities, will support agriculture monitoring, disaster management, and urban planning. The launch was conducted from the Satish Dhawan Space Centre using a proven launch vehicle. This mission is part of ISRO\'s broader strategy to expand its Earth observation constellation and support national development priorities.',
    keyDevelopments: [
      'Satellite placed in precise sun-synchronous orbit',
      'High-resolution imaging for agriculture and disaster monitoring',
      'Launch conducted from Satish Dhawan Space Centre',
      'Part of ISRO\'s Earth observation constellation expansion',
      'Enhances India\'s strategic remote sensing capabilities',
    ],
    category: 'science',
    categoryLabel: 'Science',
    trendingScore: 82,
    sourceCount: 12,
    publishedAt: hoursAgo(4),
    updatedAt: hoursAgo(1),
    entityIds: ['isro', 'india', 'nasa', 'spacex'],
    sources: [
      { sourceId: 'ndtv', sourceName: 'NDTV', sourceUrl: 'https://ndtv.com', articleUrl: 'https://ndtv.com/india-news/isro-satellite-launch', articleHeadline: 'ISRO successfully launches Earth observation satellite', publishedAt: hoursAgo(4) },
      { sourceId: 'the-hindu', sourceName: 'The Hindu', sourceUrl: 'https://thehindu.com', articleUrl: 'https://thehindu.com/sci-tech/science/isro-launch', articleHeadline: 'ISRO launches advanced Earth observation satellite', publishedAt: hoursAgo(4) },
      { sourceId: 'reuters', sourceName: 'Reuters', sourceUrl: 'https://reuters.com', articleUrl: 'https://reuters.com/science/isro-satellite-launch', articleHeadline: 'India\'s ISRO launches new Earth observation satellite', publishedAt: hoursAgo(5) },
      { sourceId: 'zee', sourceName: 'Zee News', sourceUrl: 'https://zeenews.india.com', articleUrl: 'https://zeenews.india.com/science/isro-launch', articleHeadline: 'ISRO adds another satellite to space constellation', publishedAt: hoursAgo(5) },
      { sourceId: 'bbc', sourceName: 'BBC', sourceUrl: 'https://bbc.com', articleUrl: 'https://bbc.com/news/world-asia-isro-launch', articleHeadline: 'India launches advanced observation satellite', publishedAt: hoursAgo(4) },
    ],
  },
  {
    id: 'story-4',
    title: 'Global Markets Rally as Central Banks Signal Rate Pause',
    summary:
      'Stock markets across Asia, Europe, and the Americas surged after major central banks indicated they may pause interest rate hikes, citing cooling inflation data.',
    detailedSummary:
      'Global equity markets rallied sharply as major central banks signaled a potential pause in their monetary tightening cycles. Inflation data from several economies came in below expectations, giving policymakers room to hold rates steady. The S&P 500, FTSE 100, and Nifty 50 all posted significant gains. Analysts caution that the pause does not necessarily mean rate cuts are imminent, and that future decisions will remain data-dependent.',
    keyDevelopments: [
      'US Federal Reserve signals potential rate pause',
      'European Central Bank and Bank of England indicate similar stance',
      'Cooling inflation data across major economies',
      'S&P 500, FTSE 100, and Nifty 50 post significant gains',
      'Analysts warn rate cuts are not guaranteed',
    ],
    category: 'business',
    categoryLabel: 'Business',
    trendingScore: 79,
    sourceCount: 16,
    publishedAt: hoursAgo(5),
    updatedAt: hoursAgo(1),
    entityIds: ['united-states', 'washington'],
    sources: [
      { sourceId: 'reuters', sourceName: 'Reuters', sourceUrl: 'https://reuters.com', articleUrl: 'https://reuters.com/markets/global-rally-rate-pause', articleHeadline: 'Global markets rally on rate pause signals', publishedAt: hoursAgo(5) },
      { sourceId: 'bbc', sourceName: 'BBC', sourceUrl: 'https://bbc.com', articleUrl: 'https://bbc.com/business/markets-rally', articleHeadline: 'Markets surge as central banks signal pause', publishedAt: hoursAgo(5) },
      { sourceId: 'cnn', sourceName: 'CNN', sourceUrl: 'https://cnn.com', articleUrl: 'https://cnn.com/business/global-markets-rally', articleHeadline: 'Global stocks rally on rate pause hopes', publishedAt: hoursAgo(6) },
      { sourceId: 'ndtv', sourceName: 'NDTV', sourceUrl: 'https://ndtv.com', articleUrl: 'https://ndtv.com/business/markets-rally', articleHeadline: 'Nifty, Sensex surge as global markets rally', publishedAt: hoursAgo(5) },
      { sourceId: 'the-hindu', sourceName: 'The Hindu', sourceUrl: 'https://thehindu.com', articleUrl: 'https://thehindu.com/business/markets/global-rally', articleHeadline: 'Global markets rally on rate pause signals', publishedAt: hoursAgo(6) },
      { sourceId: 'al-jazeera', sourceName: 'Al Jazeera', sourceUrl: 'https://aljazeera.com', articleUrl: 'https://aljazeera.com/economy/markets-rally', articleHeadline: 'Global markets surge on central bank signals', publishedAt: hoursAgo(6) },
    ],
  },
  {
    id: 'story-5',
    title: 'Supreme Court Reserves Verdict on Key Constitutional Challenge',
    summary:
      'The Supreme Court has reserved its verdict on a significant constitutional challenge that could reshape the relationship between state and central legislative powers.',
    detailedSummary:
      'A five-judge Constitution Bench of the Supreme Court has reserved its verdict after hearing extensive arguments on a case that tests the boundaries between state and central legislative authority. The petitioners argue that certain central legislation oversteps constitutional limits on subjects reserved for state legislatures. The government has defended the legislation as falling within the Union\'s competence. The verdict, expected in the coming weeks, could have far-reaching implications for federal governance.',
    keyDevelopments: [
      'Five-judge Constitution Bench heard arguments over six days',
      'Petitioners challenge central legislation as exceeding Union competence',
      'Government defends legislation under residual powers',
      'Verdict expected within weeks',
      'Outcome could reshape state-center legislative boundaries',
    ],
    category: 'politics',
    categoryLabel: 'Politics',
    trendingScore: 75,
    sourceCount: 10,
    publishedAt: hoursAgo(6),
    updatedAt: hoursAgo(2),
    entityIds: ['supreme-court', 'government-of-india', 'parliament-of-india', 'india', 'delhi'],
    sources: [
      { sourceId: 'ndtv', sourceName: 'NDTV', sourceUrl: 'https://ndtv.com', articleUrl: 'https://ndtv.com/india-news/supreme-court-verdict', articleHeadline: 'Supreme Court reserves verdict in key constitutional case', publishedAt: hoursAgo(6) },
      { sourceId: 'the-hindu', sourceName: 'The Hindu', sourceUrl: 'https://thehindu.com', articleUrl: 'https://thehindu.com/news/national/sc-constitutional-challenge', articleHeadline: 'SC reserves verdict on state-center power case', publishedAt: hoursAgo(6) },
      { sourceId: 'indian-express', sourceName: 'Indian Express', sourceUrl: 'https://indianexpress.com', articleUrl: 'https://indianexpress.com/article/india/sc-verdict', articleHeadline: 'Supreme Court reserves verdict on constitutional challenge', publishedAt: hoursAgo(7) },
      { sourceId: 'telegraph', sourceName: 'The Telegraph', sourceUrl: 'https://telegraph.co.uk', articleUrl: 'https://telegraph.co.uk/india/sc-constitutional-case', articleHeadline: 'India\'s Supreme Court weighs federal power case', publishedAt: hoursAgo(7) },
      { sourceId: 'bbc', sourceName: 'BBC', sourceUrl: 'https://bbc.com', articleUrl: 'https://bbc.com/news/world-asia-sc-verdict', articleHeadline: 'Supreme Court reserves verdict in key case', publishedAt: hoursAgo(6) },
    ],
  },
  {
    id: 'story-6',
    title: 'Tesla Announces New Gigafactory in India',
    summary:
      'Tesla has confirmed plans to build a new manufacturing facility in India, marking the company\'s entry into one of the world\'s largest automotive markets.',
    detailedSummary:
      'Tesla has formally announced plans to construct a new Gigafactory in India, following years of speculation and negotiation. The facility, expected to be operational within two years, will produce electric vehicles for both the domestic market and export. The announcement was welcomed by government officials who have been courting Tesla as part of a broader push for domestic manufacturing. The move is expected to create thousands of direct and indirect jobs and could accelerate the development of India\'s EV ecosystem.',
    keyDevelopments: [
      'Tesla confirms Gigafactory location in western India',
      'Facility expected to be operational within two years',
      'Production targeted at domestic market and exports',
      'Government offers incentives under manufacturing scheme',
      'Expected to create thousands of direct and indirect jobs',
    ],
    category: 'business',
    categoryLabel: 'Business',
    trendingScore: 85,
    sourceCount: 15,
    publishedAt: hoursAgo(3),
    updatedAt: hoursAgo(0.3),
    entityIds: ['tesla', 'elon-musk', 'india', 'government-of-india'],
    isBreaking: true,
    sources: [
      { sourceId: 'reuters', sourceName: 'Reuters', sourceUrl: 'https://reuters.com', articleUrl: 'https://reuters.com/business/tesla-india-gigafactory', articleHeadline: 'Tesla confirms India Gigafactory plans', publishedAt: hoursAgo(3) },
      { sourceId: 'ndtv', sourceName: 'NDTV', sourceUrl: 'https://ndtv.com', articleUrl: 'https://ndtv.com/business/tesla-india-factory', articleHeadline: 'Tesla to build Gigafactory in India', publishedAt: hoursAgo(3) },
      { sourceId: 'bbc', sourceName: 'BBC', sourceUrl: 'https://bbc.com', articleUrl: 'https://bbc.com/news/business-tesla-india', articleHeadline: 'Tesla announces first India factory', publishedAt: hoursAgo(4) },
      { sourceId: 'cnn', sourceName: 'CNN', sourceUrl: 'https://cnn.com', articleUrl: 'https://cnn.com/business/tesla-gigafactory-india', articleHeadline: 'Tesla finally comes to India', publishedAt: hoursAgo(3) },
      { sourceId: 'times-now', sourceName: 'Times Now', sourceUrl: 'https://timesnownews.com', articleUrl: 'https://timesnownews.com/business/tesla-india', articleHeadline: 'Tesla confirms Gigafactory in India', publishedAt: hoursAgo(4) },
      { sourceId: 'the-hindu', sourceName: 'The Hindu', sourceUrl: 'https://thehindu.com', articleUrl: 'https://thehindu.com/business/tesla-gigafactory', articleHeadline: 'Tesla announces manufacturing facility in India', publishedAt: hoursAgo(3) },
    ],
  },
  {
    id: 'story-7',
    title: 'New Study Reveals Alarming Decline in Global Biodiversity',
    summary:
      'A comprehensive global assessment has revealed accelerated biodiversity loss across ecosystems, with scientists calling for urgent conservation action.',
    detailedSummary:
      'A landmark study published by an international team of researchers has documented an accelerated decline in global biodiversity across terrestrial, freshwater, and marine ecosystems. The assessment, analyzing data from over a decade, found that species populations have declined by an average of 35% since the year 2000. The study identifies habitat loss, climate change, pollution, and invasive species as the primary drivers. Scientists are calling for urgent, coordinated conservation action to halt and reverse the trend.',
    keyDevelopments: [
      'Study analyzed data from over 5,000 species across 200 countries',
      'Average population decline of 35% since 2000',
      'Freshwater species most affected with 55% decline',
      'Primary drivers: habitat loss, climate change, pollution',
      'Scientists call for urgent conservation action',
    ],
    category: 'environment',
    categoryLabel: 'Environment',
    trendingScore: 71,
    sourceCount: 11,
    publishedAt: hoursAgo(7),
    updatedAt: hoursAgo(2),
    entityIds: ['united-states', 'india'],
    sources: [
      { sourceId: 'bbc', sourceName: 'BBC', sourceUrl: 'https://bbc.com', articleUrl: 'https://bbc.com/news/science-environment/biodiversity-decline', articleHeadline: 'Biodiversity declining at alarming rate, study finds', publishedAt: hoursAgo(7) },
      { sourceId: 'reuters', sourceName: 'Reuters', sourceUrl: 'https://reuters.com', articleUrl: 'https://reuters.com/environment/biodiversity-study', articleHeadline: 'Global biodiversity in sharp decline, scientists warn', publishedAt: hoursAgo(7) },
      { sourceId: 'the-hindu', sourceName: 'The Hindu', sourceUrl: 'https://thehindu.com', articleUrl: 'https://thehindu.com/sci-tech/environment/biodiversity', articleHeadline: 'Biodiversity loss accelerating globally', publishedAt: hoursAgo(8) },
      { sourceId: 'cnn', sourceName: 'CNN', sourceUrl: 'https://cnn.com', articleUrl: 'https://cnn.com/environment/biodiversity-decline', articleHeadline: 'Nature in crisis: Biodiversity declining sharply', publishedAt: hoursAgo(7) },
      { sourceId: 'al-jazeera', sourceName: 'Al Jazeera', sourceUrl: 'https://aljazeera.com', articleUrl: 'https://aljazeera.com/environment/biodiversity-study', articleHeadline: 'Global biodiversity in alarming decline', publishedAt: hoursAgo(8) },
    ],
  },
  {
    id: 'story-8',
    title: 'WHO Issues Updated Guidelines on Mental Health in the Workplace',
    summary:
      'The World Health Organization has released updated guidelines for mental health support in workplaces, urging employers to implement comprehensive wellness programs.',
    detailedSummary:
      'The WHO has published revised guidelines on mental health in the workplace, emphasizing the growing impact of work-related stress, burnout, and anxiety. The guidelines call on employers to implement comprehensive mental health programs including access to counseling, reasonable workloads, and supportive management practices. The update comes as studies show rising mental health challenges among workers globally, particularly in high-pressure industries.',
    keyDevelopments: [
      'WHO updates workplace mental health guidelines for first time in five years',
      'Calls for mandatory access to counseling services',
      'Recommends limits on after-hours work communication',
      'Highlights rising burnout in high-pressure industries',
      'Urges governments to integrate guidelines into labor law',
    ],
    category: 'health',
    categoryLabel: 'Health',
    trendingScore: 68,
    sourceCount: 9,
    publishedAt: hoursAgo(8),
    updatedAt: hoursAgo(3),
    entityIds: [],
    sources: [
      { sourceId: 'bbc', sourceName: 'BBC', sourceUrl: 'https://bbc.com', articleUrl: 'https://bbc.com/news/health-who-guidelines', articleHeadline: 'WHO issues new workplace mental health guidelines', publishedAt: hoursAgo(8) },
      { sourceId: 'reuters', sourceName: 'Reuters', sourceUrl: 'https://reuters.com', articleUrl: 'https://reuters.com/health/who-mental-health', articleHeadline: 'WHO updates workplace mental health guidance', publishedAt: hoursAgo(8) },
      { sourceId: 'the-hindu', sourceName: 'The Hindu', sourceUrl: 'https://thehindu.com', articleUrl: 'https://thehindu.com/health/who-mental-health', articleHeadline: 'WHO revises workplace mental health guidelines', publishedAt: hoursAgo(9) },
      { sourceId: 'cnn', sourceName: 'CNN', sourceUrl: 'https://cnn.com', articleUrl: 'https://cnn.com/health/who-workplace-mental-health', articleHeadline: 'WHO urges employers to prioritize mental health', publishedAt: hoursAgo(8) },
    ],
  },
  {
    id: 'story-9',
    title: 'SpaceX Achieves Historic Orbital Refueling Demonstration',
    summary:
      'SpaceX has successfully demonstrated in-orbit propellant transfer, a critical milestone for future lunar and deep space missions.',
    detailedSummary:
      'SpaceX has completed a historic demonstration of in-orbit propellant transfer between two spacecraft, a capability essential for sustained lunar exploration and future Mars missions. The demonstration involved transferring cryogenic propellant between two Starship vehicles in low Earth orbit. This capability is a key requirement for NASA\'s Artemis program, which plans to return humans to the Moon. SpaceX and NASA have been developing the technology for several years, and this successful test marks a major de-risking milestone.',
    keyDevelopments: [
      'First successful in-orbit cryogenic propellant transfer',
      'Transfer between two Starship vehicles in low Earth orbit',
      'Critical capability for NASA Artemis lunar program',
      'Marks major de-risking milestone for deep space missions',
      'Next test planned within months',
    ],
    category: 'science',
    categoryLabel: 'Science',
    trendingScore: 86,
    sourceCount: 13,
    publishedAt: hoursAgo(4),
    updatedAt: hoursAgo(0.5),
    entityIds: ['spacex', 'elon-musk', 'nasa', 'united-states'],
    isBreaking: true,
    sources: [
      { sourceId: 'reuters', sourceName: 'Reuters', sourceUrl: 'https://reuters.com', articleUrl: 'https://reuters.com/science/spacex-orbital-refueling', articleHeadline: 'SpaceX achieves orbital refueling milestone', publishedAt: hoursAgo(4) },
      { sourceId: 'bbc', sourceName: 'BBC', sourceUrl: 'https://bbc.com', articleUrl: 'https://bbc.com/news/science-spacex-refueling', articleHeadline: 'SpaceX makes history with orbital refueling', publishedAt: hoursAgo(5) },
      { sourceId: 'cnn', sourceName: 'CNN', sourceUrl: 'https://cnn.com', articleUrl: 'https://cnn.com/science/spacex-refueling-test', articleHeadline: 'SpaceX successfully demonstrates orbital refueling', publishedAt: hoursAgo(4) },
      { sourceId: 'the-hindu', sourceName: 'The Hindu', sourceUrl: 'https://thehindu.com', articleUrl: 'https://thehindu.com/sci-tech/science/spacex-refueling', articleHeadline: 'SpaceX achieves in-orbit refueling', publishedAt: hoursAgo(5) },
      { sourceId: 'ndtv', sourceName: 'NDTV', sourceUrl: 'https://ndtv.com', articleUrl: 'https://ndtv.com/science/spacex-refueling', articleHeadline: 'Historic: SpaceX demonstrates orbital refueling', publishedAt: hoursAgo(4) },
    ],
  },
  {
    id: 'story-10',
    title: 'Major Education Reform Bill Introduced in Parliament',
    summary:
      'A comprehensive education reform bill has been introduced, proposing sweeping changes to curriculum, assessment, and teacher training systems.',
    detailedSummary:
      'The government has introduced a comprehensive education reform bill in Parliament, proposing the most significant changes to the education system in decades. The bill covers curriculum modernization, assessment reform, teacher training standards, and digital infrastructure for schools. Key proposals include reducing rote learning, introducing continuous assessment, and mandating digital literacy programs. The bill has been referred to a parliamentary committee for detailed examination.',
    keyDevelopments: [
      'Bill proposes curriculum modernization across all levels',
      'Shift from rote learning to continuous assessment',
      'Mandatory digital literacy programs in all schools',
      'New teacher training and certification standards',
      'Bill referred to parliamentary committee for review',
    ],
    category: 'education',
    categoryLabel: 'Education',
    trendingScore: 64,
    sourceCount: 8,
    publishedAt: hoursAgo(9),
    updatedAt: hoursAgo(3),
    entityIds: ['parliament-of-india', 'government-of-india', 'india'],
    sources: [
      { sourceId: 'ndtv', sourceName: 'NDTV', sourceUrl: 'https://ndtv.com', articleUrl: 'https://ndtv.com/india-news/education-reform-bill', articleHeadline: 'Major education reform bill introduced', publishedAt: hoursAgo(9) },
      { sourceId: 'the-hindu', sourceName: 'The Hindu', sourceUrl: 'https://thehindu.com', articleUrl: 'https://thehindu.com/news/national/education-bill', articleHeadline: 'Education reform bill introduced in Parliament', publishedAt: hoursAgo(9) },
      { sourceId: 'indian-express', sourceName: 'Indian Express', sourceUrl: 'https://indianexpress.com', articleUrl: 'https://indianexpress.com/article/india/education-reform', articleHeadline: 'Sweeping education reform bill tabled', publishedAt: hoursAgo(10) },
      { sourceId: 'times-now', sourceName: 'Times Now', sourceUrl: 'https://timesnownews.com', articleUrl: 'https://timesnownews.com/india/education-bill', articleHeadline: 'Biggest education reform in decades', publishedAt: hoursAgo(9) },
    ],
  },
  {
    id: 'story-11',
    title: 'Climate Summit Ends with Pledge to Phase Out Coal',
    summary:
      'A major international climate summit has concluded with participating nations pledging to accelerate the phase-out of coal power and increase renewable energy investments.',
    detailedSummary:
      'The international climate summit concluded with a joint declaration from participating nations to accelerate the phase-out of unabated coal power generation. The agreement includes commitments to increase investments in renewable energy, support developing nations in their energy transitions, and establish a framework for tracking progress. While the declaration is not legally binding, it represents a significant diplomatic achievement and sets a clear direction for global energy policy.',
    keyDevelopments: [
      'Participating nations pledge to phase out unabated coal',
      'Commitment to triple renewable energy capacity by 2030',
      'Financial support package for developing nations announced',
      'Framework for tracking progress established',
      'Declaration is not legally binding but sets policy direction',
    ],
    category: 'environment',
    categoryLabel: 'Environment',
    trendingScore: 77,
    sourceCount: 14,
    publishedAt: hoursAgo(6),
    updatedAt: hoursAgo(1),
    entityIds: ['united-states', 'india'],
    sources: [
      { sourceId: 'reuters', sourceName: 'Reuters', sourceUrl: 'https://reuters.com', articleUrl: 'https://reuters.com/environment/climate-summit-coal', articleHeadline: 'Climate summit ends with coal phase-out pledge', publishedAt: hoursAgo(6) },
      { sourceId: 'bbc', sourceName: 'BBC', sourceUrl: 'https://bbc.com', articleUrl: 'https://bbc.com/news/science-environment/climate-summit', articleHeadline: 'Nations pledge to phase out coal at climate summit', publishedAt: hoursAgo(6) },
      { sourceId: 'cnn', sourceName: 'CNN', sourceUrl: 'https://cnn.com', articleUrl: 'https://cnn.com/environment/climate-summit-coal', articleHeadline: 'Historic coal phase-out pledge at climate summit', publishedAt: hoursAgo(7) },
      { sourceId: 'al-jazeera', sourceName: 'Al Jazeera', sourceUrl: 'https://aljazeera.com', articleUrl: 'https://aljazeera.com/environment/climate-summit', articleHeadline: 'Climate summit: Nations pledge coal phase-out', publishedAt: hoursAgo(7) },
      { sourceId: 'the-hindu', sourceName: 'The Hindu', sourceUrl: 'https://thehindu.com', articleUrl: 'https://thehindu.com/news/international/climate-summit', articleHeadline: 'Climate summit ends with coal phase-out declaration', publishedAt: hoursAgo(6) },
    ],
  },
  {
    id: 'story-12',
    title: 'Breakthrough in Quantum Computing Announced by Research Team',
    summary:
      'An international research team has announced a breakthrough in quantum error correction, bringing practical quantum computing closer to reality.',
    detailedSummary:
      'A team of researchers from multiple institutions has announced a significant breakthrough in quantum error correction, one of the fundamental challenges in quantum computing. The team demonstrated a new method that substantially reduces the error rate in quantum operations, a critical step toward building practical quantum computers. The breakthrough could accelerate the development of quantum computers capable of solving problems that are intractable for classical computers.',
    keyDevelopments: [
      'New method reduces quantum operation error rate by 90%',
      'Breakthrough in logical qubit error correction',
      'Brings practical quantum computing closer to reality',
      'Research published in leading scientific journal',
      'Next step: scaling to larger quantum systems',
    ],
    category: 'science',
    categoryLabel: 'Science',
    trendingScore: 73,
    sourceCount: 10,
    publishedAt: hoursAgo(10),
    updatedAt: hoursAgo(4),
    entityIds: ['nasa', 'united-states'],
    sources: [
      { sourceId: 'reuters', sourceName: 'Reuters', sourceUrl: 'https://reuters.com', articleUrl: 'https://reuters.com/technology/quantum-breakthrough', articleHeadline: 'Researchers announce quantum computing breakthrough', publishedAt: hoursAgo(10) },
      { sourceId: 'bbc', sourceName: 'BBC', sourceUrl: 'https://bbc.com', articleUrl: 'https://bbc.com/news/science-quantum-breakthrough', articleHeadline: 'Quantum error correction breakthrough announced', publishedAt: hoursAgo(10) },
      { sourceId: 'cnn', sourceName: 'CNN', sourceUrl: 'https://cnn.com', articleUrl: 'https://cnn.com/science/quantum-computing', articleHeadline: 'Major quantum computing breakthrough', publishedAt: hoursAgo(11) },
      { sourceId: 'the-hindu', sourceName: 'The Hindu', sourceUrl: 'https://thehindu.com', articleUrl: 'https://thehindu.com/sci-tech/science/quantum-breakthrough', articleHeadline: 'Quantum error correction breakthrough', publishedAt: hoursAgo(10) },
    ],
  },
  {
    id: 'story-13',
    title: 'National Cricket Team Clinches Series in Thrilling Final Match',
    summary:
      'In a nail-biting finish, the national cricket team secured a series victory with a last-over win in the final match.',
    detailedSummary:
      'The national cricket team secured a dramatic series victory, winning the final match in the last over. Chasing a challenging target, the team held its nerve to cross the line with one ball to spare. The series win marks a significant achievement for the team, which has been rebuilding after a transitional period. The victory was celebrated by fans across the country and marks a high point in the team\'s recent resurgence.',
    keyDevelopments: [
      'Series won with last-over victory in final match',
      'Captain scores match-winning century',
      'Series marks team\'s resurgence after rebuilding phase',
      'Victory celebrated by fans nationwide',
      'Next major tournament scheduled in two months',
    ],
    category: 'sports',
    categoryLabel: 'Sports',
    trendingScore: 69,
    sourceCount: 12,
    publishedAt: hoursAgo(5),
    updatedAt: hoursAgo(1),
    entityIds: ['india'],
    sources: [
      { sourceId: 'ndtv', sourceName: 'NDTV', sourceUrl: 'https://ndtv.com', articleUrl: 'https://ndtv.com/sports/cricket-series-win', articleHeadline: 'Thrilling last-over win seals series', publishedAt: hoursAgo(5) },
      { sourceId: 'times-now', sourceName: 'Times Now', sourceUrl: 'https://timesnownews.com', articleUrl: 'https://timesnownews.com/sports/cricket-series', articleHeadline: 'Last-over thriller: Team clinches series', publishedAt: hoursAgo(5) },
      { sourceId: 'republic', sourceName: 'Republic', sourceUrl: 'https://republicworld.com', articleUrl: 'https://republicworld.com/sports/cricket-series-win', articleHeadline: 'Series sealed in dramatic final over', publishedAt: hoursAgo(6) },
      { sourceId: 'zee', sourceName: 'Zee News', sourceUrl: 'https://zeenews.india.com', articleUrl: 'https://zeenews.india.com/sports/cricket-series', articleHeadline: 'Last-over win: Team takes series', publishedAt: hoursAgo(5) },
      { sourceId: 'abp', sourceName: 'ABP', sourceUrl: 'https://abplive.com', articleUrl: 'https://abplive.com/sports/cricket-series-win', articleHeadline: 'Team wins series in thrilling finale', publishedAt: hoursAgo(6) },
    ],
  },
  {
    id: 'story-14',
    title: 'Major Film Festival Awards Spotlight Independent Cinema',
    summary:
      'One of the world\'s premier film festivals has announced its awards, with independent films taking top honors across multiple categories.',
    detailedSummary:
      'A prestigious international film festival has concluded with independent films winning top awards. The jury praised the winning entries for their originality, storytelling, and social relevance. The festival, which showcased over 200 films from 40 countries, highlighted a growing trend toward independent and diverse storytelling in global cinema. Several films that premiered at the festival are expected to receive wider distribution in the coming months.',
    keyDevelopments: [
      'Independent films win top awards across multiple categories',
      'Festival showcased 200+ films from 40 countries',
      'Jury praises originality and social relevance',
      'Growing trend toward diverse storytelling in cinema',
      'Several films expected to receive wider distribution',
    ],
    category: 'culture',
    categoryLabel: 'Culture',
    trendingScore: 61,
    sourceCount: 8,
    publishedAt: hoursAgo(12),
    updatedAt: hoursAgo(5),
    entityIds: [],
    sources: [
      { sourceId: 'bbc', sourceName: 'BBC', sourceUrl: 'https://bbc.com', articleUrl: 'https://bbc.com/culture/film-festival-awards', articleHeadline: 'Independent cinema shines at film festival', publishedAt: hoursAgo(12) },
      { sourceId: 'reuters', sourceName: 'Reuters', sourceUrl: 'https://reuters.com', articleUrl: 'https://reuters.com/entertainment/film-festival', articleHeadline: 'Film festival awards spotlight independent cinema', publishedAt: hoursAgo(12) },
      { sourceId: 'cnn', sourceName: 'CNN', sourceUrl: 'https://cnn.com', articleUrl: 'https://cnn.com/entertainment/film-festival-awards', articleHeadline: 'Independent films dominate at festival', publishedAt: hoursAgo(13) },
      { sourceId: 'the-hindu', sourceName: 'The Hindu', sourceUrl: 'https://thehindu.com', articleUrl: 'https://thehindu.com/entertainment/film-festival', articleHeadline: 'Film festival celebrates independent cinema', publishedAt: hoursAgo(12) },
    ],
  },
  {
    id: 'story-15',
    title: 'US-China Trade Talks Resume After Months of Tension',
    summary:
      'Trade negotiators from the United States and China have resumed formal talks after months of escalating tensions, with both sides expressing cautious optimism.',
    detailedSummary:
      'Trade negotiators from the United States and China have resumed formal discussions after a prolonged pause. The talks focus on tariff reductions, technology transfer policies, and agricultural trade. Both sides have expressed cautious optimism, though significant differences remain. The resumption of talks follows months of escalating trade tensions that have affected global supply chains and market sentiment.',
    keyDevelopments: [
      'Formal trade talks resume after months of pause',
      'Agenda includes tariffs, technology transfer, and agriculture',
      'Both sides express cautious optimism',
      'Significant differences remain on key issues',
      'Markets respond positively to resumption of dialogue',
    ],
    category: 'world',
    categoryLabel: 'World',
    trendingScore: 80,
    sourceCount: 15,
    publishedAt: hoursAgo(4),
    updatedAt: hoursAgo(1),
    entityIds: ['united-states', 'joe-biden', 'white-house', 'washington'],
    sources: [
      { sourceId: 'reuters', sourceName: 'Reuters', sourceUrl: 'https://reuters.com', articleUrl: 'https://reuters.com/world/us-china-trade-talks', articleHeadline: 'US-China trade talks resume after months', publishedAt: hoursAgo(4) },
      { sourceId: 'bbc', sourceName: 'BBC', sourceUrl: 'https://bbc.com', articleUrl: 'https://bbc.com/news/world-us-china-trade', articleHeadline: 'US and China resume trade negotiations', publishedAt: hoursAgo(5) },
      { sourceId: 'cnn', sourceName: 'CNN', sourceUrl: 'https://cnn.com', articleUrl: 'https://cnn.com/politics/us-china-trade', articleHeadline: 'Trade talks restart as US and China seek deal', publishedAt: hoursAgo(4) },
      { sourceId: 'al-jazeera', sourceName: 'Al Jazeera', sourceUrl: 'https://aljazeera.com', articleUrl: 'https://aljazeera.com/economy/us-china-trade', articleHeadline: 'US-China trade talks resume', publishedAt: hoursAgo(5) },
      { sourceId: 'the-hindu', sourceName: 'The Hindu', sourceUrl: 'https://thehindu.com', articleUrl: 'https://thehindu.com/news/international/us-china-trade', articleHeadline: 'US, China resume formal trade talks', publishedAt: hoursAgo(4) },
    ],
  },
  {
    id: 'story-16',
    title: 'X Platform Faces Scrutiny Over Content Moderation Policies',
    summary:
      'X, formerly Twitter, is facing renewed scrutiny from regulators over its content moderation practices and the spread of misinformation on the platform.',
    detailedSummary:
      'X, the social media platform owned by Elon Musk, is facing increased regulatory scrutiny over its content moderation policies. Multiple regulators have raised concerns about the platform\'s handling of misinformation, hate speech, and election-related content. The platform has defended its approach as prioritizing free speech while removing illegal content. The scrutiny comes as several countries prepare for major elections.',
    keyDevelopments: [
      'Multiple regulators raise concerns about content moderation',
      'Focus on misinformation, hate speech, and election content',
      'Platform defends approach as free speech prioritization',
      'Scrutiny intensifies ahead of major elections',
      'Potential fines and regulatory action under discussion',
    ],
    category: 'technology',
    categoryLabel: 'Technology',
    trendingScore: 72,
    sourceCount: 11,
    publishedAt: hoursAgo(7),
    updatedAt: hoursAgo(2),
    entityIds: ['x-corp', 'elon-musk'],
    sources: [
      { sourceId: 'reuters', sourceName: 'Reuters', sourceUrl: 'https://reuters.com', articleUrl: 'https://reuters.com/technology/x-content-moderation', articleHeadline: 'X faces regulatory scrutiny over moderation', publishedAt: hoursAgo(7) },
      { sourceId: 'bbc', sourceName: 'BBC', sourceUrl: 'https://bbc.com', articleUrl: 'https://bbc.com/news/technology-x-moderation', articleHeadline: 'X under scrutiny over content policies', publishedAt: hoursAgo(7) },
      { sourceId: 'cnn', sourceName: 'CNN', sourceUrl: 'https://cnn.com', articleUrl: 'https://cnn.com/tech/x-content-moderation', articleHeadline: 'Regulators turn up heat on X', publishedAt: hoursAgo(8) },
      { sourceId: 'the-hindu', sourceName: 'The Hindu', sourceUrl: 'https://thehindu.com', articleUrl: 'https://thehindu.com/technology/x-moderation', articleHeadline: 'X faces scrutiny over content moderation', publishedAt: hoursAgo(8) },
    ],
  },
  {
    id: 'story-17',
    title: 'New National Health Survey Reveals Post-Pandemic Trends',
    summary:
      'A comprehensive national health survey has revealed shifting health trends in the post-pandemic period, including rising mental health concerns and changing healthcare access patterns.',
    detailedSummary:
      'The latest national health survey has revealed significant shifts in health trends following the pandemic. The survey, covering over 100,000 households, found rising mental health concerns, particularly among young adults, alongside changing patterns in healthcare access. Telemedicine adoption has stabilized at higher levels than pre-pandemic, while routine vaccination rates have recovered to near pre-pandemic levels in most regions.',
    keyDevelopments: [
      'Survey covers over 100,000 households nationwide',
      'Rising mental health concerns, especially among young adults',
      'Telemedicine adoption stabilizes at higher levels',
      'Routine vaccination rates recover to near pre-pandemic levels',
      'Regional disparities in healthcare access persist',
    ],
    category: 'health',
    categoryLabel: 'Health',
    trendingScore: 58,
    sourceCount: 7,
    publishedAt: hoursAgo(11),
    updatedAt: hoursAgo(4),
    entityIds: ['india'],
    sources: [
      { sourceId: 'ndtv', sourceName: 'NDTV', sourceUrl: 'https://ndtv.com', articleUrl: 'https://ndtv.com/health/national-health-survey', articleHeadline: 'National health survey reveals post-pandemic trends', publishedAt: hoursAgo(11) },
      { sourceId: 'the-hindu', sourceName: 'The Hindu', sourceUrl: 'https://thehindu.com', articleUrl: 'https://thehindu.com/health/national-survey', articleHeadline: 'Health survey shows shifting post-pandemic trends', publishedAt: hoursAgo(11) },
      { sourceId: 'indian-express', sourceName: 'Indian Express', sourceUrl: 'https://indianexpress.com', articleUrl: 'https://indianexpress.com/article/health-survey', articleHeadline: 'Post-pandemic health trends revealed in survey', publishedAt: hoursAgo(12) },
    ],
  },
  {
    id: 'story-18',
    title: 'Historic Peace Agreement Signed Between Long-Standing Rivals',
    summary:
      'A historic peace agreement has been signed between two nations that have been in conflict for decades, mediated through international diplomacy.',
    detailedSummary:
      'Two nations that have been in conflict for decades have signed a historic peace agreement, mediated through sustained international diplomacy. The agreement includes provisions for a ceasefire, mutual recognition, and a framework for resolving outstanding disputes. The international community has broadly welcomed the agreement, though implementation challenges remain. The deal is seen as a major achievement for diplomatic engagement and could reshape regional dynamics.',
    keyDevelopments: [
      'Peace agreement signed after decades of conflict',
      'Includes ceasefire, mutual recognition, and dispute framework',
      'Mediated through sustained international diplomacy',
      'International community broadly welcomes the agreement',
      'Implementation challenges remain',
    ],
    category: 'world',
    categoryLabel: 'World',
    trendingScore: 83,
    sourceCount: 17,
    publishedAt: hoursAgo(3),
    updatedAt: hoursAgo(0.5),
    entityIds: ['united-states', 'white-house', 'joe-biden', 'washington'],
    isBreaking: true,
    sources: [
      { sourceId: 'reuters', sourceName: 'Reuters', sourceUrl: 'https://reuters.com', articleUrl: 'https://reuters.com/world/peace-agreement', articleHeadline: 'Historic peace agreement signed', publishedAt: hoursAgo(3) },
      { sourceId: 'bbc', sourceName: 'BBC', sourceUrl: 'https://bbc.com', articleUrl: 'https://bbc.com/news/world-peace-deal', articleHeadline: 'Rivals sign historic peace agreement', publishedAt: hoursAgo(3) },
      { sourceId: 'cnn', sourceName: 'CNN', sourceUrl: 'https://cnn.com', articleUrl: 'https://cnn.com/world/peace-agreement', articleHeadline: 'Historic peace deal ends decades of conflict', publishedAt: hoursAgo(4) },
      { sourceId: 'al-jazeera', sourceName: 'Al Jazeera', sourceUrl: 'https://aljazeera.com', articleUrl: 'https://aljazeera.com/news/peace-agreement', articleHeadline: 'Historic peace agreement signed', publishedAt: hoursAgo(4) },
      { sourceId: 'associated-press', sourceName: 'Associated Press', sourceUrl: 'https://apnews.com', articleUrl: 'https://apnews.com/peace-agreement', articleHeadline: 'Decades-long conflict ends with peace deal', publishedAt: hoursAgo(3) },
    ],
  },
  {
    id: 'story-19',
    title: 'Startup Ecosystem Sees Record Funding in Clean Energy Sector',
    summary:
      'Clean energy startups have attracted record investment this quarter, with venture funding reaching unprecedented levels.',
    detailedSummary:
      'The clean energy startup sector has seen record venture funding this quarter, with total investments exceeding previous highs. The surge is driven by growing demand for renewable energy solutions, favorable government policies, and increasing investor confidence in the sector. Solar, wind, and energy storage startups received the largest share of funding. Analysts expect the trend to continue as countries accelerate their energy transitions.',
    keyDevelopments: [
      'Record venture funding for clean energy startups',
      'Solar, wind, and energy storage attract largest share',
      'Driven by demand, policy support, and investor confidence',
      'Funding exceeds previous quarterly highs',
      'Trend expected to continue with energy transitions',
    ],
    category: 'business',
    categoryLabel: 'Business',
    trendingScore: 66,
    sourceCount: 9,
    publishedAt: hoursAgo(9),
    updatedAt: hoursAgo(3),
    entityIds: ['tesla'],
    sources: [
      { sourceId: 'reuters', sourceName: 'Reuters', sourceUrl: 'https://reuters.com', articleUrl: 'https://reuters.com/business/clean-energy-startups', articleHeadline: 'Clean energy startups see record funding', publishedAt: hoursAgo(9) },
      { sourceId: 'cnn', sourceName: 'CNN', sourceUrl: 'https://cnn.com', articleUrl: 'https://cnn.com/business/clean-energy-funding', articleHeadline: 'Record funding flows to clean energy startups', publishedAt: hoursAgo(10) },
      { sourceId: 'the-hindu', sourceName: 'The Hindu', sourceUrl: 'https://thehindu.com', articleUrl: 'https://thehindu.com/business/clean-energy', articleHeadline: 'Clean energy sector sees record investment', publishedAt: hoursAgo(9) },
    ],
  },
  {
    id: 'story-20',
    title: 'Archaeologists Discover Ancient Civilization Ruins',
    summary:
      'Archaeologists have unearthed the ruins of a previously unknown ancient civilization, shedding new light on early human history.',
    detailedSummary:
      'A team of archaeologists has discovered the ruins of a previously unknown ancient civilization, dating back over 4,000 years. The discovery includes well-preserved structures, artifacts, and inscriptions that suggest a complex society with advanced architectural and administrative systems. The find is expected to reshape understanding of early human settlement patterns in the region.',
    keyDevelopments: [
      'Ruins date back over 4,000 years',
      'Well-preserved structures, artifacts, and inscriptions found',
      'Evidence of complex society with advanced systems',
      'Discovery expected to reshape understanding of early history',
      'Further excavation and research planned',
    ],
    category: 'culture',
    categoryLabel: 'Culture',
    trendingScore: 55,
    sourceCount: 6,
    publishedAt: hoursAgo(14),
    updatedAt: hoursAgo(6),
    entityIds: ['india'],
    sources: [
      { sourceId: 'bbc', sourceName: 'BBC', sourceUrl: 'https://bbc.com', articleUrl: 'https://bbc.com/news/science-ancient-ruins', articleHeadline: 'Ancient civilization ruins discovered', publishedAt: hoursAgo(14) },
      { sourceId: 'the-hindu', sourceName: 'The Hindu', sourceUrl: 'https://thehindu.com', articleUrl: 'https://thehindu.com/news/ancient-civilization', articleHeadline: 'Archaeologists find unknown ancient civilization', publishedAt: hoursAgo(14) },
      { sourceId: 'reuters', sourceName: 'Reuters', sourceUrl: 'https://reuters.com', articleUrl: 'https://reuters.com/science/ancient-ruins', articleHeadline: 'Ruins of unknown ancient civilization found', publishedAt: hoursAgo(15) },
    ],
  },
];

export const tickerHeadlines = [
  { label: 'BREAKING', text: 'AI companies race to develop frontier models' },
  { label: 'GLOBAL MARKETS', text: 'Stocks rally as central banks signal rate pause' },
  { label: 'INDIA', text: 'Parliament passes data protection legislation' },
  { label: 'SPACE', text: 'SpaceX achieves historic orbital refueling' },
  { label: 'CLIMATE', text: 'Summit ends with coal phase-out pledge' },
  { label: 'TECHNOLOGY', text: 'Tesla confirms Gigafactory in India' },
  { label: 'WORLD', text: 'Historic peace agreement signed' },
  { label: 'SCIENCE', text: 'Quantum computing breakthrough announced' },
];
